export const FETCH_COSTS_START = "FETCH_COSTS_START"
export const FETCH_COSTS_SUCCESS = "FETCH_COSTS_SUCCESS"
export const FETCH_COSTS_ERROR = "FETCH_COSTS_ERROR"

export const ADD_COST_START = "ADD_COST_START"
export const ADD_COST_SUCCESS = "ADD_COST_SUCCESS"
export const ADD_COST_ERROR = "ADD_COST_ERROR"

