export const SIGNIN_USER_START = "SIGNIN_USER_START"
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS"
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR"

export const SIGNUP_USER_START = "SIGNUP_USER_START"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR"

export const FETCH_COSTS_START = "FETCH_COSTS_START"
export const FETCH_COSTS_SUCCESS = "FETCH_COSTS_SUCCESS"
export const FETCH_COSTS_ERROR = "FETCH_COSTS_ERROR"

export const ADD_COST_START = "ADD_COST_START"
export const ADD_COST_SUCCESS = "ADD_COST_SUCCESS"
export const ADD_COST_ERROR = "ADD_COST_ERROR"

export const SET_USER_INFO_SUCCESS = "SET_USER_INFO_SUCCESS"
